all:
  hosts:
    gz-01:
      ansible_host: 100.117.7.75
      ansible_user: root

    gz-02:
      ansible_host: 100.79.132.125
      ansible_user: root
      mysql_server_id: 2
      mysql_buffer_pool_size: 384M
      mysql_memory_limit: 1536M
      mysql_enable_binlog: false
      mysql_restart_policy: always
      ruoyi_instance: ruoyi-admin-2
      redis_maxmemory: 256mb
      redis_memory_limit: 384m
      redis_replica_priority: 100

    gz-03:
      ansible_host: 100.92.5.116
      ansible_user: root
      mysql_server_id: 1
      mysql_buffer_pool_size: 512M
      mysql_memory_limit: 2G
      mysql_enable_binlog: true
      mysql_restart_policy: always
      ruoyi_instance: ruoyi-admin-1
      redis_maxmemory: 512mb
      redis_memory_limit: 768m

    bj-01:
      ansible_host: 100.118.69.78
      ansible_user: root
      ansible_connection: local
      mysql_server_id: 3
      mysql_buffer_pool_size: 1G
      mysql_memory_limit: 2G
      mysql_enable_binlog: true
      mysql_restart_policy: always
      mysql_source_delay: 3600
      redis_maxmemory: 128mb
      redis_memory_limit: 256m
      redis_replica_priority: 200

  children:
    gateway_nodes:
      hosts:
        gz-01:

    monitor_nodes:
      hosts:
        gz-01:

    app_nodes:
      hosts:
        gz-03:
        gz-02:

    db_master_nodes:
      hosts:
        gz-03:

    db_replica_nodes:
      hosts:
        gz-02:
        bj-01:

    db_proxy_nodes:
      hosts:
        gz-03:

    redis_master_nodes:
      hosts:
        gz-03:

    redis_replica_nodes:
      hosts:
        gz-02:
        bj-01:

    exporter_nodes:
      hosts:
        gz-01:
        gz-02:
        gz-03:
        bj-01:

    mysqld_exporter_nodes:
      hosts:
        gz-02:
        gz-03:
        bj-01:

    ops_nodes:
      hosts:
        bj-01:

    diary_nodes:
      hosts:
        bj-01:

    alertmanager_nodes:
      hosts:
        bj-01: