---
- name: Ensure MySQL directory exists
  ansible.builtin.file:
    path: "{{ docker_root }}/backend/mysql"
    state: directory
    mode: "0755"

- name: Render MySQL replica env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ docker_root }}/backend/mysql/.env"
    mode: "0600"
  notify: restart mysql

- name: Render MySQL replica compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_root }}/backend/mysql/docker-compose.yml"
    mode: "0644"
  notify: restart mysql
