---
- name: Deploy monitor stack
  hosts: monitor_nodes
  become: true
  roles:
    - role: monitor-stack
      tags: [monitor, prometheus, grafana, blackbox]

- name: Deploy node exporter
  hosts: exporter_nodes
  become: true
  roles:
    - role: node-exporter
      tags: [exporter, node-exporter]

- name: Deploy mysqld exporter
  hosts: mysqld_exporter_nodes
  become: true
  vars_files:
    - ../vault/secrets.yml
  roles:
    - role: mysqld-exporter
      tags: [exporter, mysqld-exporter]

- name: Deploy alertmanager stack
  hosts: alertmanager_nodes
  become: true
  vars_files:
    - ../vault/secrets.yml
  roles:
    - role: alertmanager
      tags: [alertmanager, alerting, feishu]
