---
- import_playbook: setup_infra.yml
- import_playbook: setup_registry.yml
- import_playbook: setup_database.yml
- import_playbook: setup_redis.yml
- import_playbook: setup_app.yml
- import_playbook: setup_diary.yml
- import_playbook: setup_gateway.yml
- import_playbook: setup_monitor.yml
- import_playbook: setup_ops.yml
- import_playbook: setup_backup.yml